package lab1.mybatis.model;

import java.util.Set;

public class Author {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Wed Apr 27 22:00:45 EEST 2022
     */
    private Integer id;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.FULL_AUTHOR_NAME
     *
     * @mbg.generated Thu Apr 28 12:36:08 EEST 2022
     */
    private String fullAuthorName;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.LASTNAME
     *
     * @mbg.generated Thu Apr 28 12:36:08 EEST 2022
     */
    private String lastname;




    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.NAME
     *
     * @mbg.generated Wed Apr 27 22:00:45 EEST 2022
     */
    private String name;

    private Set<Library> libraries;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.ID
     *
     * @return the value of PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Wed Apr 27 22:00:45 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.ID
     *
     * @param id the value for PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Wed Apr 27 22:00:45 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.FULL_AUTHOR_NAME
     *
     * @return the value of PUBLIC.AUTHOR.FULL_AUTHOR_NAME
     *
     * @mbg.generated Thu Apr 28 12:36:08 EEST 2022
     */
    public String getFullAuthorName() {
        return fullAuthorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.FULL_AUTHOR_NAME
     *
     * @param fullAuthorName the value for PUBLIC.AUTHOR.FULL_AUTHOR_NAME
     *
     * @mbg.generated Thu Apr 28 12:36:08 EEST 2022
     */
    public void setFullAuthorName(String fullAuthorName) {
        this.fullAuthorName = fullAuthorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.LASTNAME
     *
     * @return the value of PUBLIC.AUTHOR.LASTNAME
     *
     * @mbg.generated Thu Apr 28 12:36:08 EEST 2022
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.LASTNAME
     *
     * @param lastname the value for PUBLIC.AUTHOR.LASTNAME
     *
     * @mbg.generated Thu Apr 28 12:36:08 EEST 2022
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.NAME
     *
     * @return the value of PUBLIC.AUTHOR.NAME
     *
     * @mbg.generated Wed Apr 27 22:00:45 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.NAME
     *
     * @param name the value for PUBLIC.AUTHOR.NAME
     *
     * @mbg.generated Wed Apr 27 22:00:45 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    public Set<Library> getLibraries() {
        return libraries;
    }

    public void setLibraries(Set<Library> libraries) {
        this.libraries = libraries;
    }
}