package lab1.mybatis.model;

import java.util.Set;

public class Library {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LIBRARY.ID
     *
     * @mbg.generated Wed Apr 27 22:00:45 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LIBRARY.NAME
     *
     * @mbg.generated Wed Apr 27 22:00:45 EEST 2022
     */
    private String name;


    private Set<Author> authorsWithBooks;

    public Set<Author> getAuthorsWithBooks() {
        return authorsWithBooks;
    }

    public void setAuthorsWithBooks(Set<Author> authorsWithBooks) {
        this.authorsWithBooks = authorsWithBooks;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LIBRARY.ID
     *
     * @return the value of PUBLIC.LIBRARY.ID
     *
     * @mbg.generated Wed Apr 27 22:00:45 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LIBRARY.ID
     *
     * @param id the value for PUBLIC.LIBRARY.ID
     *
     * @mbg.generated Wed Apr 27 22:00:45 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LIBRARY.NAME
     *
     * @return the value of PUBLIC.LIBRARY.NAME
     *
     * @mbg.generated Wed Apr 27 22:00:45 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LIBRARY.NAME
     *
     * @param name the value for PUBLIC.LIBRARY.NAME
     *
     * @mbg.generated Wed Apr 27 22:00:45 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}