package lab1.mybatis.dao;

import java.util.List;
import java.util.Set;

import lab1.mybatis.model.Author;
import lab1.mybatis.model.Library;
import org.mybatis.cdi.Mapper;

@Mapper
public interface LibraryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LIBRARY
     *
     * @mbg.generated Wed Apr 27 22:00:45 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LIBRARY
     *
     * @mbg.generated Wed Apr 27 22:00:45 EEST 2022
     */
    int insert(Library record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LIBRARY
     *
     * @mbg.generated Wed Apr 27 22:00:45 EEST 2022
     */
    Library selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LIBRARY
     *
     * @mbg.generated Wed Apr 27 22:00:45 EEST 2022
     */
    List<Library> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LIBRARY
     *
     * @mbg.generated Wed Apr 27 22:00:45 EEST 2022
     */
    int updateByPrimaryKey(Library record);

    Set<Author> selectAuthorsWithBooks(int libraryId);
}